### ISSUE TITLE
Cannot connect: Unknown_Protocol.

### ISSUE THREAD

**Issue by Kocrachon** [tenable/nessrest#100]
Hey all, sorry if this is a dumb question.

Currently I am using the restful API and I am trying to switch to this python method. However, for some reason, I am not able to connect to the host via my python script. it complains ab out the 'protocol. Not sure if it may be related to me switching my server to use port 443 instead of the default 8834.

Here is the odd error I get on it.
```
[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590) for https://ec2-ip-ip-ip-ip.compute-1.amazonaws.com:443/session.
```

If I do something like this, my API calls work using the regular resful api. 

```user@$ curl -k -X POST -H 'Content-Type: application/json' -d '{"username":"username","password":"password"}' https://ec2-ip-ip-ip-ip.compute-1.amazonaws.com/scans```

```
But, if I try this with my python script, it just sits and idles and eventually spits out the above error.


from nessrest import ness6rest

print 'Setting Connection Details'
nessus_url = "https://ec2-ip-ip-ip-ip.compute-1.amazonaws.com"
login = "username"
password = "password"

print 'connecting'
scan = ness6rest.Scanner(url=nessus_url, login=login, password=password, insecure=True)

print 'setting policy'
scan.policy_set(name="TestPolicy")

print 'setting target'
scan.scan_add(targets="ec2-10-100-10-72.compute-1.amazonaws.com")

print 'starting scan'
scan.scan_run()
```
I have also tried replacing the nessus URL to look like this, but to no avail. 

```
nessus_url = "https://ec2-ip-ip-ip-ip.compute-1.amazonaws.com:443"
```

EDIT: When I try from another EC2 instance, it works fine. One thing I am thinking of, is my company blocks all non-standard ports. So only ports like 80, 443, 3389, 22, etc are open. So this is part of the reason I ask about ports, it seems like its having issues. But its hard for me to say. But my companies firewall is the whole reason I put Nessus on port 443. 

EDIT2: Here is some ipython output.

```
---------------------------------------------------------------------------
SSLException                              Traceback (most recent call last)
<ipython-input-8-3c76815f5f15> in <module>()
----> 1 scan = ness6rest.Scanner(url="https://ec2-ip-ip-ip-ip.compute-1.amazonaws.com", login="username", password="password")

/Library/Python/2.7/site-packages/nessrest/ness6rest.pyc in __init__(self, url, login, password, api_akey, api_skey, insecure, ca_bundle)
    110         else:
    111             # Initial login to get our token for all subsequent transactions
--> 112             self._login(login, password)
    113
    114             # Register a call to the logout action automatically

/Library/Python/2.7/site-packages/nessrest/ness6rest.pyc in _login(self, login, password)
    128                     extra={"username": self.auth[0], "password": self.auth[1]},
    129                     private=True,
--> 130                     retry=False)
    131
    132         try:

/Library/Python/2.7/site-packages/nessrest/ness6rest.pyc in action(self, action, method, extra, files, json_req, download, private, retry)
    244                 return req.content
    245         except requests.exceptions.SSLError as ssl_error:
--> 246             raise SSLException('%s for %s.' % (ssl_error, url))
    247         except requests.exceptions.ConnectionError:
    248             raise Exception("Could not connect to %s.\nExiting!\n" % url)

```

**Comment by freetest** [comment]
@Kocrachon how did you fix it?

**Comment by Kocrachon** [comment]
@freetest I will provide you with my example in the morning of what I changed. I dont have the script on me, its on my work machine.

**Comment by mokuso** [comment]
If it works from another ec2 instance then its not an issue with the port.  I'd check the following:
- Does the security group on the instance have a rule allowing the connection?
- Is the outbound traffic being proxied from the company network?
