### ISSUE TITLE
HTML Reports Empty - Fixed

### ISSUE THREAD

**Issue by ghostop14** [tenable/nessrest#104]
When running the samples in the scripts directory with an export format of html, the report was coming back empty.  I found that the issue was that the export request did not request any "chapter" sections and it appeared the default is now none.  So in ness6rest.py in the download_scan function I added another export_format check to add the "chapters" parameter:

        if (export_format=="db"):
            data = {"format":"db","password":dbpasswd}
        else:
            if (export_format=="html"):
                chapters="vuln_hosts_summary;vuln_by_host"
                data = {'format': export_format, "chapters": chapters}
            else:
                data = {'format': export_format}

**Comment by mokuso** [comment]
The chapters parameter was added in PR #94
