### ISSUE TITLE
Impossible to run a standard "basic network scan" via nessrest?

### ISSUE THREAD

**Issue by adrianloy** [tenable/nessrest#107]
Hello,

I try to use nessrest to run a basic network scan, just like I would do in Nessus original GUI, where you do not have to create a policy to do that. Now I try to do that using nessrest, but as I get it, you cannot run a scan with a template only, you need to specify a policy.
This wouldn't be that big problem, if I could easily create a policy that will lead to a basic network scan, but I cannot find the plugin IDs that I have to pass to scan.policy_add to achieve this.

Is it possible to run a basic network scan via nessrest without creating a policy? If not, which plugin IDs are needed to create the policy to achieve a basic network scan?

**Comment by mokuso** [comment]
I just merged fix from PR 106, this should allow you to run a scan using a template as follows:

```
>>> scan.scan_add('192.168.111.195', template='basic', name='My Basic Scan')
>>> scan.scan_run()
```
