### ISSUE TITLE
ness6rest is not defined

### ISSUE THREAD

**Issue by Pika-Boo** [tenable/nessrest#109]
Module is being imported, Issue when trying to use ness6rest

![screenshot_1](https://cloud.githubusercontent.com/assets/7687847/24282472/a102fc22-1085-11e7-9c1b-6e9d3bbd0009.png)

**Comment by streckc** [comment]
Object is Scanner in the ness6rest.py file.  If you are in the base directory of the repository, you can load and initialize like this...

>>> from nessrest.ness6rest import Scanner
>>> scan = Scanner(url="https://nessusscanner:8834", login="username", password="password")

Thanks,
-chad
