### ISSUE TITLE
Unable to create a new scan 

### ISSUE THREAD

**Issue by ranjanp75** [tenable/nessrest#135]
I am trying to create a scan using python nessus client but it keeps throwing the following error
{
  "error": "API is not available"
}
Please help me out with this issue. Thank you

**Comment by johndekroon** [comment]
Which version of Nessus are you using?

**Comment by ranjanp75** [comment]
The version I am using is Nessus 7

**Comment by streckc** [comment]
Nessus 7 has removed the ability to launch a scan using the API.

> Be aware that you will lose the ability to add new users or use the API for scanning, so do this only when you are ready.

The recommendation is to use the Tenable.IO API for launching and managing scans and data.  Link to Tenable.IO Python SDK... https://github.com/tenable/pyTenable

-chad

**Comment by ranjanp75** [comment]
Thanks for the reply. But our requirement is to use api for on premises
deployment of messes but not the cloud api. So is there a possibility of
trying out 6.11 version of Nessus . Thank you so much

**Comment by streckc** [comment]
That would be a question for your Tenable sales contact or talking to the reseller you purchased Nessus from.
