### ISSUE TITLE
Is this package support Nessus 7 ? 

### ISSUE THREAD

**Issue by BLKStone** [tenable/nessrest#137]
Hello everyone, my Nessus version is 7.0.3 on WINDOWS platform. I wrote some test code but got some errors.

My test code is as below:

```python
# nessrest
def test_case2():
    from nessrest import ness6rest
    nessus_url = 'https://127.0.0.1:8834'
    username = 'admin'
    password = 'admin'
    scanner = ness6rest.Scanner(url=nessus_url, login=username, password=password, insecure=True)
    scanner.scan_add(targets="192.168.1.10")
    scanner.scan_run()
```

When this code tries to create a scan task (scan_add), it got some error message

```python
Traceback (most recent call last):
  File "test_octoeye.py", line 51, in <module>
    test_case1()
  File "test_octoeye.py", line 44, in test_case1
    logged_scanner.scan_add(targets="192.168.1.10")
  File "C:\Python27\lib\site-packages\nessrest\ness6rest.py", line 684, in scan_add
    self.scan_uuid = self.res["scan"]["uuid"]
KeyError: 'scan'

# -------------------------------------------------------------
URL     : https://127.0.0.1:8834/scans 
METHOD  : POST
RESPONSE: 400


{
  "error": "Invalid 'name' field"
}
```

How can I solve this problem ?
If this package does not support Nessus 7, is there any suggestions for replacement? (python nessus client is prefered)

**Comment by sjcliffe** [comment]
My understanding is that Tenable have dropped API support in version 7.

**Comment by streckc** [comment]
As @sjcliffe said, Nessus 7 has removed the ability to launch a scan using the API.

> Be aware that you will lose the ability to add new users or use the API for scanning, so do this only when you are ready.

The recommendation is to use the Tenable.IO API for launching and managing scans and data.

-chad

**Comment by streckc** [comment]
Link to Tenable.IO Python SDK... https://github.com/tenable/pyTenable

**Comment by BLKStone** [comment]
@streckc @sjcliffe Many thanks!
