### ISSUE TITLE
Please upload a new version to pypi

### ISSUE THREAD

**Issue by alexpdp7** [tenable/nessrest#43]
With change d2953f17943d4f9b871314b2399385236689ebe5 , as without that, one cannot install nessrest using pip.

**Comment by invisiblethreat** [comment]
Will try to get to this today.

**Comment by alexpdp7** [comment]
I'm using master and it works beautifully, so I'm not in a hurry of having an official version in pypi... if you had a release scheduled for some time, I can wait...

**Comment by invisiblethreat** [comment]
This is all ad hoc, so there's no schedule at all. Missed a build for these fixes. You can now find it at https://pypi.python.org/packages/source/n/nessrest/nessrest-0.14.tar.gz
