### ISSUE TITLE
_get_feed() broken after upgrading to 6.3.5

### ISSUE THREAD

**Issue by maaren** [tenable/nessrest#47]
'feed' is no longer returned by /server/properties after upgrading to 6.3.5. Wrapping a try, except around self.ver_feed = self.res['feed'] fixed it for me.

**Comment by invisiblethreat** [comment]
Boo regressions. Will look at this today. It has been replaced by another call in the API which escapes me at the moment.

**Comment by maaren** [comment]
This raises the question. How stable is the API? Any idea?

**Comment by jplee3** [comment]
Ag, I just ran into this as well in 6.3.6 :(

Any updates on the issue at hand?

**Comment by maaren** [comment]
As I said, wrap it with a try, or just comment the call in ness6rest.py:

#        self._get_feed()

**Comment by jplee3** [comment]
Yea, I ended up commenting it out and things worked. Do you see the same properties when you actually return the URI as well though where feed is completely missing from the list (even with the professional version)?

**Comment by invisiblethreat** [comment]
New method on the way to get this info back:
```
+    def _get_scanner_id(self):
+        '''
+        Pull in information about scanner. The ID is necessary, everything else
+        is "nice to have" for debugging.
+        '''
+        self.action(action="scanners", method="get")
+
+        for scanner in self.res:
+                if scanner["type"] == "local":
+                    self.scanner_id = scanner['id']
+                    self.ver_plugins = scanner['loaded_plugin_set']
+                    self.ver_gui = scanner['ui_version']
+                    self.ver_svr = scanner['engine_version']
+                    self.ver_feed = scanner['license']['type']
+
```

**Comment by invisiblethreat** [comment]
There's currently a PR to get the temp fix in place, and I'll work on getting this into place next week.

**Comment by jplee3** [comment]
Just checking in again - when does it sound like the fix will go in at this point?

**Comment by invisiblethreat** [comment]
Sorry for missing this. Update is merged.
