### ISSUE TITLE
DELETE /scans/{scan_id}/history returns an error

### ISSUE THREAD

**Issue by liberza** [tenable/nessrest#62]
When trying to delete scan result history via the API, I'm getting an error. Specifically, I ran the following in the Python interactive interpreter:

```python
>>> scanner.action(action="scans/1/history", method="DELETE", extra={'history_id':1})
*****************START ERROR*****************
JSON    :
{"history_id": 1}
{}
HEADERS :
{'X-ApiKeys': 'accessKey=791188a5491fa435581582080682c237acea64d2b3d2154c8fcaacf7932778d9; secretKey=d6d1499513383ca4e09a5026d22a36f5e6736bd60762bd60d334b92eccfa00e0', 'Content-type': 'application/json', 'Accept': 'text/plain'}
URL     : https://localhost:8834/scans/1/history 
METHOD  : DELETE
RESPONSE: 405


{
  "error": "The requested method is not allowed for this URL"
}

******************END ERROR******************
```

I also tried using Nessus' API documentation's built-in tester to try it, with the same result:

![nessus_deletehistory](https://cloud.githubusercontent.com/assets/4465144/10413785/b8da3ae8-6f84-11e5-9c92-d08b87696ec3.png)

I realize this means the problem is probably with Nessus' API itself, but I'm not sure where the best place would be to report that.

**Comment by bsnyder788** [comment]
I am seeing the same exact issue with the Nessus API as well. 

Version info:
Nessus Vulnerability Scanner
Nessus REST API Reference v. 6.4.3

**Comment by invisiblethreat** [comment]
According to an engine dev, this needs to an administrative user.

**Comment by invisiblethreat** [comment]
Please funnel these sorts of issues through support.tenable.com, so they will get sent to the correct groups in a more timely manner than I got to this issue. :)
