### ISSUE TITLE
"error": "Invalid Credentials"

### ISSUE THREAD

**Issue by freetest** [tenable/nessrest#73]
scan.policy_set(name='port')
scans = scan.scan_add(targets='123.123.123.123,12.12.12.12',name='test223')
scan.scan_run()
scan.scan_results()

when  i put many targets like 66. 

****************_START ERROR**_**************
Traceback (most recent call last):
  File "/Users/wx/PycharmProjects/untitled/ds.py", line 44, in <module>
JSON    :
    scan.scan_results()
{}
  File "/Users/wx/python-env/lib/python2.7/site-packages/nessrest/ness6rest.py", line 902, in scan_results
{}
HEADERS :
    self._scan_status()
  File "/Users/wx/python-env/lib/python2.7/site-packages/nessrest/ness6rest.py", line 705, in _scan_status
{'X-Cookie': 'token=017', 'Content-type': 'application/json', 'Accept': 'text/plain'}
    for scan in self.res["scans"]:
URL     : https://1.1.1.1:8834/scans?folder_id=196 
KeyError: 'scans'
METHOD  : get
RESPONSE: 401

{
  "error": "Invalid Credentials"
}

*****************_END ERROR**_***************
****************_START ERROR**_**************
JSON    :
{}
{}
HEADERS :
{'X-Cookie': 'token=017', 'Content-type': 'application/json', 'Accept': 'text/plain'}
URL     : https://0.0.0.0:8834/session 
METHOD  : delete
RESPONSE: 401

{
  "error": "Invalid Credentials"
}

*****************_END ERROR**_***************

Process finished with exit code 1

if i put two targets i not error

**Comment by invisiblethreat** [comment]
There's no 'Scanner' object in your included code. You have to login, or provide a valid API key.

**Comment by freetest** [comment]
@invisiblethreat  i allready set the login .  

scan = ness6rest.Scanner(url="https://10.166.52.148:8834", login="root", password="nessusroot", insecure=True)

scan.policy_set(name='portscan')
scans = scan.scan_add(targets='0.0.0.239,0.0.0.47,0.0.0.215,0.0.0.39,0.0.0.237,0.0.0.32,0.0.0.228,0.0.0.191,0.0.0.204,0.0.0.118,0.0.0.37,0.0.0.30,0.0.0.40,0.0.0.222,0.0.0.250,0.0.0.140,0.0.0.168,0.0.0.144,0.0.0.57,0.0.0.18,0.0.0.249,0.0.0.207,0.0.0.216,0.0.0.15,0.0.0.212,0.0.0.254,0.0.0.181,0.0.0.124,0.0.0.123,0.0.0.24,0.0.0.56,0.0.0.126,0.0.0.22,0.0.0.198,0.0.0.31,0.0.0.173,0.0.0.202,0.0.0.129,0.0.0.167,0.0.0.203,0.0.0.44,0.0.0.211,0.0.0.223,0.0.0.42,0.0.0.205,0.0.0.121,0.0.0.58,0.0.0.192,0.0.0.238,0.0.0.217,0.0.0.128,0.0.0.29,0.0.0.23,0.0.0.52,0.0.0.43,0.0.0.213,0.0.0.182,0.0.0.108,0.0.0.145,0.0.0.189,0.0.0.122,0.0.0.179,0.0.0.20,0.0.0.227,0.0.0.206,0.0.0.193',name='test223')
scan.scan_run()
scan.scan_results()
kbs = scan.download_kbs()
for hostname in kbs.keys():
	lists = kbs[hostname].split('SYNScanner/CnxTime1000/')


this my full code.



if  targets = scans = scan.scan_add(targets='0.0.0.239,0.0.0.47,0.0.0.215',name='test223')

it will be worked .

is the session timeout?

Or I can download KBS  By specifying scan_uuid?

**Comment by mokuso** [comment]
May have been session timeout. Fixed by #105
