### ISSUE TITLE
Problem with Nessus REST API mod:     from pynessus import Nessus

### ISSUE THREAD

**Issue by pythoncode17** [tenable/nessrest#82]
I trying to login to our nessus server using a python 
My OS: Window 7
Using: Python 3.4
Using: Nessus 6.7.0
> pip install pynessus
Successfully installed pynessus-0.9.1

My program

from pynessus import Nessus
localhost="https://777.777.7.77:8834"
server = Nessus(localhost, 8834)
if server.login(User("swgoat", "IknowNothingSeenothingHearnothing!")):
	print("Success!")
else:
	print("Fail!")

Program returns error when I run it:
  File "E:\quarterly\RestApi.py", line 1, in <module>
    from pynessus import Nessus
ImportError: cannot import name 'Nessus'

So I tried
> pip install python-nessus
    ImportError: No module named 'nessus'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ngillem\AppData\Local\Temp\1\pip-build-clt5hx5_\python-nessus\

How can I get this to run.

**Comment by invisiblethreat** [comment]
This project maintains 'nessrest' not 'pynessus'
