### ISSUE TITLE
Rest API python 3.5.2

### ISSUE THREAD

**Issue by RaymondArias** [tenable/nessrest#90]
The rest api for nessus occasionally, about half the time, throws exceptions when running on python 3.5.2. But the api runs on python 3.4.4 works correctly.

**Comment by invisiblethreat** [comment]
Any exceptions in particular?

**Comment by RaymondArias** [comment]
It throws these exceptions:

![exceptions](https://cloud.githubusercontent.com/assets/15129320/16632362/b47895f8-4378-11e6-93b1-e76c3cd87d3e.PNG)

**Comment by RaymondArias** [comment]
Here is the code its running:

![codesnippet](https://cloud.githubusercontent.com/assets/15129320/16632399/da583ab2-4378-11e6-8954-9a9999dc5d8d.PNG)

**Comment by RaymondArias** [comment]
Do you have any idea the API is throwing these exceptions? The company I work for is interested in why it only does this when running python 3.5.2.

**Comment by invisiblethreat** [comment]
The connection is being reset and throwing the error in the Requests library, not our library. You can see the error cascade from your code, through our code, and into the Requests library.

**Comment by RaymondArias** [comment]
So its basically an error with Python 3.5.2? Is there a way around this? Or just wait for an update with python to fix this bug?
