### ISSUE TITLE
PUT https://scanner:8834/policies/  error

### ISSUE THREAD

**Issue by duke-cheng** [tenable/nessrest#92]
HEADERS :
{'X-Cookie': 'token=04f6cdcd096fd3d2a4942e13f8ec489e6a465631fb564028', 'Content-type': 'application/json', 'Accept': 'text/plain'}
URL     : https://scanner:8834/policies/ 
METHOD  : put
RESPONSE: 405

{
  "error": "The requested method is not allowed for this URL"
}

**Comment by invisiblethreat** [comment]
That method is "GET" as per <your nessus url>/api#/resources/policies/list
